### PR TITLE
Search and sort made realtime fixes (#5)

### LINKED ISSUE #5: Filter and sort functionality don't work in realtime
**Issue**
Filter and sort functionality on members page does work in realtime.
User have click on search button

**Would you like work on this**
I would like to work on this and make the functionality realtime.

### PR DESCRIPTION
**Pull request by ashutoshc8101**
Fixes #5 
Search and sort functionality is made realtime

### CODE REVIEW

File: src/app/members/members.component.ts [hunk 1]
```diff
@@ -47,11 +47,14 @@ export class MembersComponent implements OnInit {
   }
   private _filter(value: string, arr : object[] ): object[] {
     const filterValue = value.toLowerCase();
+    let longestName = arr[0];
     return arr.filter(option => this._check(option, filterValue));
+
+
   }
   private _check(option : object, filterValue : string){
-    var a = option['name'].toLowerCase().includes(filterValue);
```
Comment (ashutoshc8101) [inline src/app/members/members.component.ts]: Abhishek Sir, please change includes back to match.

**Review by ashutoshc8101 — COMMENTED** [review]
self reviewed

**Review by abhishek0220 — APPROVED** [review]
